/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "LCD.h"
#include "isrRX.h"
#include "emFile.h"
#include "ADC.h"
#include "Pin_ADC_aliases.h"
#include "Pin_ADC.h"
#include "PWM.h"
#include "Counter.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "isr_1.h"
#include "foto_transistor_aliases.h"
#include "foto_transistor.h"
#include "ADC2.h"
#include "Pin_ADC2_aliases.h"
#include "Pin_ADC2.h"
#include "UART_IntClock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "emFile_SPI0.h"
#include "emFile_SPI0_PVT.h"
#include "emFile_mosi0_aliases.h"
#include "emFile_mosi0.h"
#include "emFile_Clock_1.h"
#include "emFile_miso0_aliases.h"
#include "emFile_miso0.h"
#include "emFile_sclk0_aliases.h"
#include "emFile_sclk0.h"
#include "emFile_SPI0_CS_aliases.h"
#include "emFile_SPI0_CS.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "ADC2_IRQ.h"
#include "ADC2_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

